kind: Namespace
apiVersion: v1
metadata:
  name: akarinext-web
  labels:
    name: akarinext-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akarinext-web-deployment
  namespace: akarinext-web
  labels:
    app: akarinext-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akarinext-web
  template:
    metadata:
      labels:
        app: akarinext-web
    spec:
      containers:
      - name: akarinext-web
        image: ghcr.io/akarinext/www.akarinext.org:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
          name: akarinext-web-config
---
apiVersion: v1
kind: Service
metadata:
  name: akarinext-web
  namespace: akarinext-web
spec:
  selector:
    app: akarinext-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
