apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akarinext-web

resources:
  - deployment.yaml
  - psql.yaml
  - psql-claim.yaml

images:
- name: ghcr.io/akarinext/www.akarinext.org
  newTag: latest
