apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akarinext-web

resources:
- deployment.yaml
- cloudnative-pg.yaml

images:
- name: ghcr.io/akarinext/www.akarinext.org
  newName: ghcr.io/akarinext/www.akarinext.org
  newTag: sha-fc2750b
