name:  Reviewdog

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  biome:
    name: Linter 🧹
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
      - name: lint
        uses: mongolyy/reviewdog-action-biome@v1.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
